name: ðŸž Bug
description: File a bug report issue
title: "[ðŸž] "
labels:
    - Bug
    - Needs Triage
body:
    - type: checkboxes
      id: check-search
      attributes:
          label: Is there an existing issue for this?
          description: >-
              Please search to see if an issue already exists for the bug you
              encountered.
          options:
              - label: I have searched the existing issues
                required: true
    - type: textarea
      id: description
      attributes:
          label: Describe the bug
          description: |
              A clear and concise description of what the bug is.
              If applicable, add screenshots and log to help explain your problem.
      validations:
          required: true
    - type: textarea
      id: debug-output
      attributes:
          label: Debug Output
          description: |
              Steps to get debug output:
              1. Do x
              2. Do y
              3. Do z
              5. Upload the debug output here
      validations:
          required: true
    - type: textarea
      id: additional-context
      attributes:
          label: Anything else?
          description: >
              Links? References? Anything that will give us more context about
              the issue you are encountering!

              Tip: You can attach images or log files by clicking this area to
              highlight it and then dragging files in.
